### PR TITLE
Updated README, rake tasks, and TravisCI build targets.

### PR DESCRIPTION
**Pull request by jdantonio**
# Deprecate in lieu of Concurrent Ruby

Several months ago @headius suggested that the code in this gem be merged into [Concurrent Ruby](http://www.concurrent-ruby.com) and [this gem be deprecated](https://github.com/ruby-concurrency/concurrent-ruby/issues/83). Subsequently we:
- Created the [ruby-concurrency](https://github.com/ruby-concurrency) organization within GitHub
- Moved several gems from the personal accounts of @headius and @jdantonio to the `ruby-concurrency` organization
- Merged the code from `ruby-atomic` into `concurrent-ruby` (numerous merged commits prior to [PR #153](https://github.com/ruby-concurrency/concurrent-ruby/pull/153))
- Released [v0.7.0](https://github.com/ruby-concurrency/concurrent-ruby/releases/tag/v0.7.0) which included the merged code
- Began troubleshooting issues with the native extensions [from the community](https://github.com/ruby-concurrency/concurrent-ruby/issues/181)
- Discussed different ways to handle [C/Java Native Extensions](https://github.com/ruby-concurrency/concurrent-ruby/issues/186) in the upcoming 0.8.0 release
- Spiked an implementation which [retained the Java native code within the core concurrent-ruby gem](https://github.com/ruby-concurrency/concurrent-ruby/pull/197)...
- ...while moving the [native C code into an extension gem](https://github.com/ruby-concurrency/concurrent-ruby-ext)
## Recommendation

If the original plan discussed in [Concurrent Ruby Issue #83](https://github.com/ruby-concurrency/concurrent-ruby/issues/83) is still the plan then I recommend we merge this PR and make the [final atomic release](https://github.com/ruby-concurrency/concurrent-ruby/issues/83#issuecomment-43423384) suggested by @headius back in May.

Thoughts? @headius @pitr-ch @mighe @chrisseaton @obrok @lucasallan

### CODE REVIEW

**Comment by jdantonio** [comment]
We've released concurrent-ruby and concurrent-ruby-ext 0.8.0. Are there any objections to me merging this PR and publishing one final release of this gem?

@headius @pitr-ch @mighe @chrisseaton @obrok @lucasallan

**Comment by chrisseaton** [comment]
Not from me.

**Comment by pitr-ch** [comment]
No, go ahead :+1:

**Comment by mighe** [comment]
:+1:

**Comment by headius** [comment]
Go for it. Did I give you the rights you need, or do I need to do something?

**Comment by jdantonio** [comment]
@headius You shouldn't have to do anything. I just wanted to get everyone's buy-in before moving ahead.

**Comment by jdantonio** [comment]
Done! I've built the two gem packages and pushed them to Rubygems.

**Pull request merged**
